# Primo Secret: username e password
apiVersion: v1
kind: Secret
metadata:
  name: secret-credentials
type: Opaque
data:
  username: bWFyaW8=  # mario (Base64)
  password: Y2lhbzEyMw==  # ciao123 (Base64)

---
# Secondo Secret: esempio da un file
apiVersion: v1
kind: Secret
metadata:
  name: secret-from-file
type: Opaque
data:
  config: Y29uZmlnIGRhdGEgZXNzZW1waW8=  # config data esempio (Base64)

---
# Pod per leggere i Secret
apiVersion: v1
kind: Pod
metadata:
  name: read-secrets
spec:
  containers:
  - name: secret-reader
    image: busybox
    command: ["sh", "-c", "sleep 3600"]  # Mantiene il pod in esecuzione
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: secret-credentials
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: secret-credentials
          key: password
    volumeMounts:
    - name: secret-volume
      mountPath: "/etc/secret-volume"
      readOnly: true
  volumes:
  - name: secret-volume
    secret:
      secretName: secret-from-file

